export const EDITOR_MODELS = [
  { id: "m1", src: "/models/model-01.webp", name: "Amara", categories: ["women"] },
  { id: "m2", src: "/models/model-02.webp", name: "Mina", categories: ["women"] },
  { id: "m3", src: "/models/model-03.webp", name: "Sofia", categories: ["women"] },
  { id: "m4", src: "/models/model-04.webp", name: "Clara", categories: ["women"] },
  { id: "m5", src: "/models/model-05.webp", name: "Leila", categories: ["women"] },
  { id: "m6", src: "/models/model-06.webp", name: "Nora", categories: ["women"] },
  { id: "m7", src: "/models/model-07.webp", name: "Imani", categories: ["women"] },
  { id: "m8", src: "/models/model-08.webp", name: "Elise", categories: ["women"] },
  { id: "m9", src: "/models/model-09.webp", name: "Naomi", categories: ["women"] },
  { id: "m10", src: "/models/model-10.webp", name: "Maya", categories: ["women"] },
  { id: "m11", src: "/models/model-11.webp", name: "Aaliyah", categories: ["plusSize", "women"] },
  { id: "m12", src: "/models/model-12.webp", name: "Grace", categories: ["plusSize", "women"] },
  { id: "m13", src: "/models/model-13.webp", name: "Camila", categories: ["plusSize", "women"] },
  { id: "m14", src: "/models/model-14.webp", name: "Hana", categories: ["plusSize", "women"] },
  { id: "m15", src: "/models/model-15.webp", name: "Priya", categories: ["plusSize", "women"] },
  { id: "m16", src: "/models/model-16.webp", name: "Lucia", categories: ["plusSize", "women"] },
  { id: "m17", src: "/models/model-17.webp", name: "Rina", categories: ["plusSize", "women"] },
  { id: "m18", src: "/models/model-18.webp", name: "Zuri", categories: ["plusSize", "women"] },
  { id: "m19", src: "/models/model-19.webp", name: "Ella", categories: ["plusSize", "women"] },
  { id: "m20", src: "/models/model-20.webp", name: "Mei", categories: ["plusSize", "women"] },
  { id: "m21", src: "/models/model-21.webp", name: "Marcus", categories: ["men"] },
  { id: "m22", src: "/models/model-22.webp", name: "Jun", categories: ["men"] },
  { id: "m23", src: "/models/model-23.webp", name: "Adrian", categories: ["men"] },
  { id: "m24", src: "/models/model-24.webp", name: "Ethan", categories: ["men"] },
  { id: "m25", src: "/models/model-25.webp", name: "Ravi", categories: ["men"] },
  { id: "m26", src: "/models/model-26.webp", name: "Omar", categories: ["men"] },
  { id: "m27", src: "/models/model-27.webp", name: "Leo", categories: ["men"] },
  { id: "m28", src: "/models/model-28.webp", name: "Theo", categories: ["men"] },
] as const;

export type EditorModel = (typeof EDITOR_MODELS)[number];
