const url  ="https://cdn.aiclotheschangers.app/image"
export const EDITOR_MODELS = [
  { id: "m1", src: `${url}/model-01.webp`, name: "Amara", categories: ["women"] },
  { id: "m2", src: `${url}/model-02.webp`, name: "Mina", categories: ["women"] },
  { id: "m3", src: `${url}/model-03.webp`, name: "Sofia", categories: ["women"] },
  { id: "m4", src: `${url}/model-04.webp`, name: "Clara", categories: ["women"] },
  { id: "m5", src: `${url}/model-05.webp`, name: "Leila", categories: ["women"] },
  { id: "m6", src: `${url}/model-06.webp`, name: "Nora", categories: ["women"] },
  { id: "m7", src: `${url}/model-07.webp`, name: "Imani", categories: ["women"] },
  { id: "m8", src: `${url}/model-08.webp`, name: "Elise", categories: ["women"] },
  { id: "m9", src: `${url}/model-09.webp`, name: "Naomi", categories: ["women"] },
  { id: "m10", src: `${url}/model-10.webp`, name: "Maya", categories: ["women"] },
  { id: "m11", src: `${url}/model-11.webp`, name: "Aaliyah", categories: ["plusSize", "women"] },
  { id: "m12", src: `${url}/model-12.webp`, name: "Grace", categories: ["plusSize", "women"] },
  { id: "m13", src: `${url}/model-13.webp`, name: "Camila", categories: ["plusSize", "women"] },
  { id: "m14", src: `${url}/model-14.webp`, name: "Hana", categories: ["plusSize", "women"] },
  { id: "m15", src: `${url}/model-15.webp`, name: "Priya", categories: ["plusSize", "women"] },
  { id: "m16", src: `${url}/model-16.webp`, name: "Lucia", categories: ["plusSize", "women"] },
  { id: "m17", src: `${url}/model-17.webp`, name: "Rina", categories: ["plusSize", "women"] },
  { id: "m18", src: `${url}/model-18.webp`, name: "Zuri", categories: ["plusSize", "women"] },
  { id: "m19", src: `${url}/model-19.webp`, name: "Ella", categories: ["plusSize", "women"] },
  { id: "m20", src: `${url}/model-20.webp`, name: "Mei", categories: ["plusSize", "women"] },
  { id: "m21", src: `${url}/model-21.webp`, name: "Marcus", categories: ["men"] },
  { id: "m22", src: `${url}/model-22.webp`, name: "Jun", categories: ["men"] },
  { id: "m23", src: `${url}/model-23.webp`, name: "Adrian", categories: ["men"] },
  { id: "m24", src: `${url}/model-24.webp`, name: "Ethan", categories: ["men"] },
  { id: "m25", src: `${url}/model-25.webp`, name: "Ravi", categories: ["men"] },
  { id: "m26", src: `${url}/model-26.webp`, name: "Omar", categories: ["men"] },
  { id: "m27", src: `${url}/model-27.webp`, name: "Leo", categories: ["men"] },
  { id: "m28", src: `${url}/model-28.webp`, name: "Theo", categories: ["men"] },
] as const;

export type EditorModel = (typeof EDITOR_MODELS)[number];
